### PR TITLE
Include duplicate pin name in pin label array, remove pinNames from component template

### PR DESCRIPTION
**Pull request by andrii-balitskyi**
Closes https://github.com/tscircuit/easyeda-converter/issues/90
Screenshot

### CODE REVIEW

**Review by seveibar — APPROVED** [review]

**Comment by andrii-balitskyi** [comment]
@seveibar test and benchmark workflow fails. Do I need to update test snapshots that you recently introduced?

**Comment by seveibar** [comment]
@andrii-balitskyi it's snapshotting the `pinLabels` section of the code, so you can fix just by running `bun test --update-snapshots` (it uses a bun-native text snapshot)

**Comment by andrii-balitskyi** [comment]
@seveibar it still fails 🤔 . Also, I had to update some of the svgs, could you take a look at them?

**Comment by seveibar** [comment]
For the SVGs, that's a regression, make sure to run `bun i` to get the latest dependencies.

**Comment by andrii-balitskyi** [comment]
@seveibar oh my bad, thanks a ton!

**Pull request merged**
