### PR TITLE
Support `T~` text shapes

### PR DESCRIPTION
**Pull request by andrii-balitskyi**
Closes https://github.com/tscircuit/easyeda-converter/issues/58.

Adding support for `T~` shapes and fixing scripts/add-test-for-part.ts as it was giving me the following error:

image

- **Support  text shape**
- **Fix script adding part test, run the script to add test**

### CODE REVIEW

**Review by seveibar — APPROVED** [review]
nice! Would be good to have a snapshot on this one because i'm not sure if we converted properly just looking at the code

**Comment by andrii-balitskyi** [comment]
@seveibar I added the snapshot but it doesn't seem to look right 😅

**Comment by seveibar** [comment]
@andrii-balitskyi i love it! Yea I think requiring snapshots for every visual project (most recently I introduced it to snippets) is essential, it's just too hard to know if the code is correct otherwise.

Luckily for easyeda we know we have the correct answer here:

image

**Comment by seveibar** [comment]
@andrii-balitskyi actually comparing these, it seems to be a stroke width issue. So I don't think you caused an issue here. To fix this, the strokeWidth/stroke_width needs to be set to a reasonable default or whatever the raweasy says it is. But I think your PR is good, we should create an issue to fix the stroke widths

**Comment by andrii-balitskyi** [comment]
Cool! 

Created an issue https://github.com/tscircuit/easyeda-converter/issues/79

**Pull request merged**
