### PR TITLE
Sort pin labels in largest to smallest order

### PR DESCRIPTION
**Pull request by DhairyaMajmudar**
-> Sorting pins in largest to smallest order in generated tsx file

cleses: #105 
/claim: #105

### CODE REVIEW

**Comment by DhairyaMajmudar** [comment]
cc: @seveibar

**Comment by seveibar** [comment]
@DhairyaMajmudar can you confirm that they are sorted properly in a test

**Review by seveibar — CHANGES_REQUESTED** [review]
the bug may not exist anymore...

**Comment by DhairyaMajmudar** [comment]
> the bug may not exist anymore...

Gotcha, let me close this PR then

**Pull request closed without merging**
